# Generated by Django 4.1.3 on 2022-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prdlstReportNo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('prdlstNm', models.CharField(max_length=200)),
                ('prdkind', models.CharField(max_length=200)),
                ('rawmtrl', models.TextField()),
                ('allergy', models.TextField()),
                ('manufacture', models.CharField(max_length=200)),
                ('nutrient', models.TextField(blank=True)),
                ('seller', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
